### ISSUE TITLE
Create vcpkg

### ISSUE THREAD

**Issue by bangusi** [PBfordev/wxAutoExcel#1]
No issue per se but would be great to have  this library in vcpkg

**Comment by PBfordev** [comment]
I doubt that vcpkg would accept a library with such a small/nonexistant user base. Not even wxSQLite or wxPDFDoc, which I consider among more popular 3rd party wxWidgets libraries, are there...

**Comment by bangusi** [comment]
OK. I had no idea there is any gate keeping at vcpkg. I thought any library author can package their library for distribution via vcpkg. 
Anyhow , until now I was not aware of wxAutoExcel so was looking for an easier way to try out the library

**Comment by PBfordev** [comment]
I actually do not know whether there are any barriers to accept the library, I just guessed.

Anyhow, (1) I do not use Vcpkg myself so I could not do it, (2) Unforutnately there are no versions or releases of wxAutoExcel, just the master branch that gets updated without changing the library version.
