### ISSUE TITLE
Wrong upper lower case in #include

### ISSUE THREAD

**Issue by mat-ieu** [PBfordev/wxAutoExcel#2]
In wxAutoExcel.h, instead of 
#include "wx/wxAutoExcelGridlines.h"
it should be
#include "wx/wxAutoExcelGridLines.h"
to make mingw32 compilers happy.

**Comment by PBfordev** [comment]
Thanks for the info. I decided to change the file names instead, so that the file name capitalization matches the class one.

Having file names camelcased is probably a bad idea but since this library is Windows only and Windows is de facto case insensitive, I guess it is more or less OK.
